/**
 * Edit tool module.
 *
 * Supports three modes:
 * - Replace mode (default): oldText/newText replacement with fuzzy matching
 * - Patch mode: structured diff format with explicit operation type
 * - Hashline mode: line-addressed edits using content hashes for integrity
 *
 * The mode is determined by the `edit.mode` setting.
 */
import * as fs from "node:fs/promises";
import * as nodePath from "node:path";
import type { AgentTool, AgentToolContext, AgentToolResult, AgentToolUpdateCallback } from "@oh-my-pi/pi-agent-core";
import { StringEnum } from "@oh-my-pi/pi-ai";
import { type LibEditOperation, type LibEditResult, libEditApply } from "@oh-my-pi/pi-natives/libedit";
import { type Static, Type } from "@sinclair/typebox";
import { renderPromptTemplate } from "../config/prompt-templates";
import {
	createLspWritethrough,
	type FileDiagnosticsResult,
	flushLspWritethroughBatch,
	type WritethroughCallback,
	writethroughNoop,
} from "../lsp";
import hashlineDescription from "../prompts/tools/hashline.md" with { type: "text" };
import patchDescription from "../prompts/tools/patch.md" with { type: "text" };
import replaceDescription from "../prompts/tools/replace.md" with { type: "text" };
import type { ToolSession } from "../tools";
import { checkAutoGeneratedFile, checkAutoGeneratedFileContent } from "../tools/auto-generated-guard";
import {
	invalidateFsScanAfterDelete,
	invalidateFsScanAfterRename,
	invalidateFsScanAfterWrite,
} from "../tools/fs-cache-invalidation";
import { outputMeta } from "../tools/output-meta";
import { enforcePlanModeWrite, resolvePlanPath } from "../tools/plan-mode-guard";
import { findMatch } from "./fuzzy";
import { buildCompactHashlineDiffPreview } from "./hashline";
import { type EditToolDetails, getLspBatchRequest } from "./shared";
// Internal imports
import { EditMatchError, type Operation } from "./types";

// ═══════════════════════════════════════════════════════════════════════════
// Re-exports
// ═══════════════════════════════════════════════════════════════════════════

// Application
export { applyPatch, defaultFileSystem, previewPatch } from "./applicator";
// Diff generation
export * from "./diff";

// Hashline
export * from "./hashline";
// Normalization
export * from "./normalize";
export type { EditRenderContext, EditToolDetails } from "./shared";
// Rendering
export { editToolRenderer, getLspBatchRequest } from "./shared";
export * from "./types";

// ═══════════════════════════════════════════════════════════════════════════
// Schemas
// ═══════════════════════════════════════════════════════════════════════════

const replaceEditSchema = Type.Object({
	path: Type.String({ description: "File path (relative or absolute)" }),
	old_text: Type.String({ description: "Text to find (fuzzy whitespace matching enabled)" }),
	new_text: Type.String({ description: "Replacement text" }),
	all: Type.Optional(Type.Boolean({ description: "Replace all occurrences (default: unique match required)" })),
});

const patchEditSchema = Type.Object({
	path: Type.String({ description: "File path" }),
	op: Type.Optional(
		StringEnum(["create", "delete", "update"], {
			description: "Operation (default: update)",
		}),
	),
	rename: Type.Optional(Type.String({ description: "New path for move" })),
	diff: Type.Optional(Type.String({ description: "Diff hunks (update) or full content (create)" })),
});

export type ReplaceParams = Static<typeof replaceEditSchema>;
export type PatchParams = Static<typeof patchEditSchema>;

/**
 * Pattern matching hashline display format prefixes: `LINE#ID:CONTENT`, `#ID:CONTENT`, and `+ID:CONTENT`.
 * A plus-prefixed form appears in diff-like output and should be treated as hashline metadata too.
 */
const HASHLINE_PREFIX_RE = /^\s*(?:>>>|>>)?\s*(?:\+?\s*(?:\d+\s*#\s*|#\s*)|\+)\s*[ZPMQVRWSNKTXJBYH]{2}:/;
const HASHLINE_PREFIX_PLUS_RE = /^\s*(?:>>>|>>)?\s*\+\s*(?:\d+\s*#\s*|#\s*)?[ZPMQVRWSNKTXJBYH]{2}:/;

/** Pattern matching a unified-diff added-line `+` prefix (but not `++`). Does NOT match `-` to avoid corrupting Markdown list items. */
const DIFF_PLUS_RE = /^[+](?![+])/;

/**
 * Strip hashline display prefixes and diff `+` markers from replacement lines.
 *
 * Models frequently copy the `LINE#ID  ` prefix from read output into their
 * replacement content, or include unified-diff `+` prefixes. Both corrupt the
 * output file. This strips them heuristically before application.
 */
export function stripNewLinePrefixes(lines: string[]): string[] {
	// Hashline prefixes are highly specific to read output and are usually stripped only when
	// *every* non-empty line carries one. If a line is prefixed as `+ID:`, strip that
	// prefix while leaving other `+` lines untouched to avoid corrupting mixed snippets.
	let hashPrefixCount = 0;
	let diffPlusHashPrefixCount = 0;
	let diffPlusCount = 0;
	let nonEmpty = 0;
	for (const l of lines) {
		if (l.length === 0) continue;
		nonEmpty++;
		if (HASHLINE_PREFIX_RE.test(l)) hashPrefixCount++;
		if (HASHLINE_PREFIX_PLUS_RE.test(l)) diffPlusHashPrefixCount++;
		if (DIFF_PLUS_RE.test(l)) diffPlusCount++;
	}
	if (nonEmpty === 0) return lines;

	const stripHash = hashPrefixCount > 0 && hashPrefixCount === nonEmpty;
	const stripPlus =
		!stripHash && diffPlusHashPrefixCount === 0 && diffPlusCount > 0 && diffPlusCount >= nonEmpty * 0.5;
	if (!stripHash && !stripPlus && diffPlusHashPrefixCount === 0) return lines;

	return lines.map(l => {
		if (stripHash) return l.replace(HASHLINE_PREFIX_RE, "");
		if (stripPlus) return l.replace(DIFF_PLUS_RE, "");
		if (diffPlusHashPrefixCount > 0 && HASHLINE_PREFIX_PLUS_RE.test(l)) return l.replace(HASHLINE_PREFIX_RE, "");
		return l;
	});
}

/**
 * Strip hashline display prefixes only (no diff markers).
 *
 * Unlike {@link stripNewLinePrefixes} which also handles `+` diff markers,
 * this only strips `LINE#ID:` / `#ID:` prefixes. Used by the write tool
 * where diff markers are not applicable.
 *
 * Returns the original array reference when no stripping is needed.
 */
export function stripHashlinePrefixes(lines: string[]): string[] {
	let hashPrefixCount = 0;
	let nonEmpty = 0;
	for (const l of lines) {
		if (l.length === 0) continue;
		nonEmpty++;
		if (HASHLINE_PREFIX_RE.test(l)) hashPrefixCount++;
	}
	if (nonEmpty === 0 || hashPrefixCount !== nonEmpty) return lines;
	return lines.map(l => l.replace(HASHLINE_PREFIX_RE, ""));
}

export function hashlineParseText(edit: string[] | string | null): string[] {
	if (edit === null) return [];
	if (typeof edit === "string") {
		const normalizedEdit = edit.endsWith("\n") ? edit.slice(0, -1) : edit;
		edit = normalizedEdit.replaceAll("\r", "").split("\n");
	}
	return stripNewLinePrefixes(edit);
}

const linesSchema = Type.Union([
	Type.Array(Type.String(), { description: "content (preferred format)" }),
	Type.String(),
	Type.Null(),
]);

const locSchema = Type.Union(
	[
		Type.Literal("append"),
		Type.Literal("prepend"),
		Type.Object({ append: Type.String({ description: "anchor" }) }),
		Type.Object({ prepend: Type.String({ description: "anchor" }) }),
		Type.Object({
			line: Type.String({ description: "anchor" }),
		}),
		Type.Object({
			block: Type.Object({
				pos: Type.String({ description: "anchor" }),
				end: Type.String({ description: "limit position" }),
			}),
		}),
	],
	{ description: "insert location" },
);

const hashlineEditSchema = Type.Object(
	{
		loc: locSchema,
		content: linesSchema,
	},
	{ additionalProperties: false },
);

const hashlineEditParamsSchema = Type.Object(
	{
		path: Type.String({ description: "path" }),
		edits: Type.Array(hashlineEditSchema, { description: "edits over $path" }),
		delete: Type.Optional(Type.Boolean({ description: "If true, delete $path" })),
		move: Type.Optional(Type.String({ description: "If set, move $path to $move" })),
	},
	{ additionalProperties: false },
);

export type HashlineToolEdit = Static<typeof hashlineEditSchema>;
export type HashlineParams = Static<typeof hashlineEditParamsSchema>;

function mergeDiagnosticsWithWarnings(
	diagnostics: FileDiagnosticsResult | undefined,
	warnings: string[],
): FileDiagnosticsResult | undefined {
	if (warnings.length === 0) return diagnostics;
	const warningMessages = warnings.map(warning => `patch: ${warning}`);
	if (!diagnostics) {
		return {
			server: "patch",
			messages: warningMessages,
			summary: `Patch warnings: ${warnings.length}`,
			errored: false,
		};
	}
	return {
		...diagnostics,
		messages: [...warningMessages, ...diagnostics.messages],
		summary: `${diagnostics.summary}; Patch warnings: ${warnings.length}`,
	};
}

// ═══════════════════════════════════════════════════════════════════════════
// Tool Class
// ═══════════════════════════════════════════════════════════════════════════

type TInput = typeof replaceEditSchema | typeof patchEditSchema | typeof hashlineEditParamsSchema;

export type EditMode = "replace" | "patch" | "hashline";

export const DEFAULT_EDIT_MODE: EditMode = "hashline";

const EDIT_MODES = ["replace", "patch", "hashline"] as const satisfies readonly EditMode[];
const EDIT_ID = Object.fromEntries(EDIT_MODES.map(mode => [mode, mode])) satisfies Record<string, EditMode>;
export const normalizeEditMode = (mode?: string | null): EditMode | undefined => EDIT_ID[mode ?? ""];

function isHashlineParams(params: ReplaceParams | PatchParams | HashlineParams): params is HashlineParams {
	return "edits" in params;
}

function isReplaceParams(params: ReplaceParams | PatchParams | HashlineParams): params is ReplaceParams {
	return "old_text" in params && "new_text" in params;
}

function normalizeReplaceResultMessage(message: string, path: string): string {
	const occurrencesMatch = /^Replaced (\d+) occurrences? in /u.exec(message);
	if (occurrencesMatch) {
		return `Successfully replaced ${occurrencesMatch[1]} occurrences in ${path}`;
	}
	if (/^Replaced text in /u.test(message)) {
		return `Successfully replaced text in ${path}`;
	}
	return message;
}

function normalizeReplaceErrorMessage(message: string, path: string): string {
	if (message.startsWith("No match found in ")) {
		return `Could not find a close enough match in ${path}.`;
	}
	return message;
}

/**
 * Edit tool implementation.
 *
 * Creates replace-mode, patch-mode, or hashline-mode behavior based on session settings.
 */
export class EditTool implements AgentTool<TInput> {
	readonly name = "edit";
	readonly label = "Edit";
	readonly nonAbortable = true;
	readonly concurrency = "exclusive";
	readonly strict = true;

	readonly #allowFuzzy: boolean;
	readonly #fuzzyThreshold: number;
	readonly #writethrough: WritethroughCallback;
	readonly #editMode?: EditMode | null;

	constructor(private readonly session: ToolSession) {
		const {
			PI_EDIT_FUZZY: editFuzzy = "auto",
			PI_EDIT_FUZZY_THRESHOLD: editFuzzyThreshold = "auto",
			PI_EDIT_VARIANT: envEditVariant = "auto",
		} = Bun.env;

		if (envEditVariant && envEditVariant !== "auto") {
			const editMode = normalizeEditMode(envEditVariant);
			if (!editMode) {
				throw new Error(`Invalid PI_EDIT_VARIANT: ${envEditVariant}`);
			}
			this.#editMode = editMode;
		}

		switch (editFuzzy) {
			case "true":
			case "1":
				this.#allowFuzzy = true;
				break;
			case "false":
			case "0":
				this.#allowFuzzy = false;
				break;
			case "auto":
				this.#allowFuzzy = session.settings.get("edit.fuzzyMatch");
				break;
			default:
				throw new Error(`Invalid PI_EDIT_FUZZY: ${editFuzzy}`);
		}
		switch (editFuzzyThreshold) {
			case "auto":
				this.#fuzzyThreshold = session.settings.get("edit.fuzzyThreshold");
				break;
			default:
				this.#fuzzyThreshold = parseFloat(editFuzzyThreshold);
				if (Number.isNaN(this.#fuzzyThreshold) || this.#fuzzyThreshold < 0 || this.#fuzzyThreshold > 1) {
					throw new Error(`Invalid PI_EDIT_FUZZY_THRESHOLD: ${editFuzzyThreshold}`);
				}
				break;
		}

		const enableLsp = session.enableLsp ?? true;
		const enableDiagnostics = enableLsp && session.settings.get("lsp.diagnosticsOnEdit");
		const enableFormat = enableLsp && session.settings.get("lsp.formatOnWrite");
		this.#writethrough = enableLsp
			? createLspWritethrough(session.cwd, { enableFormat, enableDiagnostics })
			: writethroughNoop;
	}

	/**
	 * Determine edit mode dynamically based on current model.
	 * This is re-evaluated on each access so tool definitions stay current when model changes.
	 */
	get mode(): EditMode {
		if (this.#editMode) return this.#editMode;
		// 1. Check if edit mode is explicitly set for this model
		const activeModel = this.session.getActiveModelString?.();
		const modelVariant = this.session.settings.getEditVariantForModel(activeModel);
		if (modelVariant) return modelVariant;
		// 2. Check if model contains "-spark" substring (default to replace mode)
		if (activeModel?.includes("-spark")) return "replace";
		// 3. Check if edit mode is explicitly set in session settings
		const settingsMode = normalizeEditMode(this.session.settings.get("edit.mode"));
		if (settingsMode) return settingsMode;
		// 4. Default to DEFAULT_EDIT_MODE
		return DEFAULT_EDIT_MODE;
	}

	/**
	 * Dynamic description based on current edit mode (which depends on current model).
	 */
	get description(): string {
		switch (this.mode) {
			case "patch":
				return renderPromptTemplate(patchDescription);
			case "hashline":
				return renderPromptTemplate(hashlineDescription);
			default:
				return renderPromptTemplate(replaceDescription);
		}
	}

	/**
	 * Dynamic parameters schema based on current edit mode (which depends on current model).
	 */
	get parameters(): TInput {
		switch (this.mode) {
			case "patch":
				return patchEditSchema;
			case "hashline":
				return hashlineEditParamsSchema;
			default:
				return replaceEditSchema;
		}
	}

	async #runLibEdit(
		methodName: "hashline" | "patch" | "replace",
		input: unknown,
		files: Array<{ path: string; content: string }>,
		displayPaths: Array<{ absolute: string; display: string }>,
	): Promise<{ result: LibEditResult; operations: LibEditOperation[] }> {
		try {
			return await libEditApply(methodName, input, files, {
				allowFuzzy: this.#allowFuzzy,
				threshold: this.#fuzzyThreshold,
			});
		} catch (error) {
			let message = error instanceof Error ? error.message : String(error);
			for (const { absolute, display } of displayPaths) {
				message = message.replaceAll(absolute, display);
			}
			throw new Error(message);
		}
	}

	async #applyLibEditOperations(
		operations: LibEditOperation[],
		signal: AbortSignal | undefined,
		batchRequest: { id: string; flush: boolean } | undefined,
	): Promise<FileDiagnosticsResult | undefined> {
		let diagnostics: FileDiagnosticsResult | undefined;
		let deleted = false;
		for (const operation of operations) {
			if (operation.kind === "write") {
				if (operation.content === undefined) {
					throw new Error(`libedit write operation missing content for ${operation.path}`);
				}
				const result = await this.#writethrough(
					operation.path,
					operation.content,
					signal,
					Bun.file(operation.path),
					batchRequest,
				);
				if (result) {
					diagnostics = result;
				}
				continue;
			}

			deleted = true;
			try {
				await Bun.file(operation.path).unlink();
			} catch (error) {
				if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
					throw error;
				}
			}
		}

		if (deleted && batchRequest?.flush && !diagnostics) {
			const flushedDiagnostics = await flushLspWritethroughBatch(batchRequest.id, this.session.cwd, signal);
			diagnostics ??= flushedDiagnostics;
		}

		return diagnostics;
	}

	#invalidateLibEditResult(result: LibEditResult): void {
		for (const change of [result.change, ...result.changes]) {
			if (change.new_path) {
				invalidateFsScanAfterRename(change.path, change.new_path);
			} else if (change.op === "delete") {
				invalidateFsScanAfterDelete(change.path);
			} else {
				invalidateFsScanAfterWrite(change.path);
			}
		}
	}

	async execute(
		_toolCallId: string,
		params: ReplaceParams | PatchParams | HashlineParams,
		signal?: AbortSignal,
		_onUpdate?: AgentToolUpdateCallback<EditToolDetails, TInput>,
		context?: AgentToolContext,
	): Promise<AgentToolResult<EditToolDetails, TInput>> {
		const batchRequest = getLspBatchRequest(context?.toolCall);

		if (this.mode === "hashline") {
			if (!isHashlineParams(params)) {
				throw new Error("Invalid edit parameters for hashline mode.");
			}
			const { path, edits, delete: deleteFile, move } = params;

			enforcePlanModeWrite(this.session, path, { op: deleteFile ? "delete" : "update", move });

			if (path.endsWith(".ipynb") && edits?.length > 0) {
				throw new Error("Cannot edit Jupyter notebooks with the Edit tool. Use the NotebookEdit tool instead.");
			}

			const absolutePath = resolvePlanPath(this.session, path);
			const resolvedMove = move ? resolvePlanPath(this.session, move) : undefined;
			if (resolvedMove === absolutePath) {
				throw new Error("move path is the same as source path");
			}
			const sourceExists = await fs.exists(absolutePath);
			const isMoveOnly = Boolean(resolvedMove) && edits.length === 0;

			if (deleteFile) {
				if (sourceExists) {
					await fs.unlink(absolutePath);
				}
				invalidateFsScanAfterDelete(absolutePath);
				return {
					content: [{ type: "text", text: `Deleted ${path}` }],
					details: {
						diff: "",
						op: "delete",
						meta: outputMeta().get(),
					},
				};
			}

			if (isMoveOnly && resolvedMove) {
				if (!sourceExists) {
					throw new Error(`File not found: ${path}`);
				}
				const parentDir = nodePath.dirname(resolvedMove);
				if (parentDir && parentDir !== ".") {
					await fs.mkdir(parentDir, { recursive: true });
				}
				// Preserve exact bytes for move-only operations, including binary files.
				await fs.rename(absolutePath, resolvedMove);
				invalidateFsScanAfterRename(absolutePath, resolvedMove);
				return {
					content: [{ type: "text", text: `Moved ${path} to ${move}` }],
					details: {
						diff: "",
						op: "update",
						move,
						meta: outputMeta().get(),
					},
				};
			}
			const fileSeeds: Array<{ path: string; content: string }> = [];
			if (sourceExists) {
				const rawContent = await fs.readFile(absolutePath, "utf-8");
				await checkAutoGeneratedFileContent(rawContent, path);
				fileSeeds.push({ path: absolutePath, content: rawContent });
			}
			const { result, operations } = await this.#runLibEdit(
				"hashline",
				{
					path: absolutePath,
					edits,
					...(resolvedMove ? { move: resolvedMove } : {}),
				},
				fileSeeds,
				[
					{ absolute: absolutePath, display: path },
					...(resolvedMove && move ? [{ absolute: resolvedMove, display: move }] : []),
				],
			);
			const diagnostics = await this.#applyLibEditOperations(operations, signal, batchRequest);
			this.#invalidateLibEditResult(result);

			const meta = outputMeta()
				.diagnostics(diagnostics?.summary ?? "", diagnostics?.messages ?? [])
				.get();

			const resultText =
				result.change.op === "create" ? `Created ${path}` : move ? `Moved ${path} to ${move}` : `Updated ${path}`;
			const diffText = result.diff ?? "";
			const preview = buildCompactHashlineDiffPreview(diffText);
			const summaryLine = `Changes: +${preview.addedLines} -${preview.removedLines}${preview.preview ? "" : " (no textual diff preview)"}`;
			const warningsBlock = result.warnings.length ? `\n\nWarnings:\n${result.warnings.join("\n")}` : "";
			const previewBlock = preview.preview ? `\n\nDiff preview:\n${preview.preview}` : "";
			return {
				content: [
					{
						type: "text",
						text: `${resultText}\n${summaryLine}${previewBlock}${warningsBlock}`,
					},
				],
				details: {
					diff: diffText,
					firstChangedLine: result.first_changed_line,
					diagnostics,
					op: result.change.op,
					move,
					meta,
				},
			};
		}

		if (this.mode === "patch") {
			if (isHashlineParams(params) || isReplaceParams(params)) {
				throw new Error("Invalid edit parameters for patch mode.");
			}
			const { path, op: rawOp, rename, diff } = params;

			// Normalize unrecognized operations to "update"
			const op: Operation = rawOp === "create" || rawOp === "delete" ? rawOp : "update";

			enforcePlanModeWrite(this.session, path, { op, move: rename });
			const resolvedPath = resolvePlanPath(this.session, path);
			const resolvedRename = rename ? resolvePlanPath(this.session, rename) : undefined;

			if (path.endsWith(".ipynb")) {
				throw new Error("Cannot edit Jupyter notebooks with the Edit tool. Use the NotebookEdit tool instead.");
			}
			if (rename?.endsWith(".ipynb")) {
				throw new Error("Cannot edit Jupyter notebooks with the Edit tool. Use the NotebookEdit tool instead.");
			}

			await checkAutoGeneratedFile(resolvedPath, path);
			const fileSeeds: Array<{ path: string; content: string }> = [];
			if (await fs.exists(resolvedPath)) {
				fileSeeds.push({ path: resolvedPath, content: await fs.readFile(resolvedPath, "utf-8") });
			}
			const { result, operations } = await this.#runLibEdit(
				"patch",
				{ path: resolvedPath, op, rename: resolvedRename, diff },
				fileSeeds,
				[
					{ absolute: resolvedPath, display: path },
					...(resolvedRename && rename ? [{ absolute: resolvedRename, display: rename }] : []),
				],
			);
			const diagnostics = await this.#applyLibEditOperations(operations, signal, batchRequest);
			this.#invalidateLibEditResult(result);
			const effRename = result.change.new_path ? rename : undefined;

			let resultText: string;
			switch (result.change.op) {
				case "create":
					resultText = `Created ${path}`;
					break;
				case "delete":
					resultText = `Deleted ${path}`;
					break;
				case "update":
					resultText = effRename ? `Updated and moved ${path} to ${effRename}` : `Updated ${path}`;
					break;
			}

			const mergedDiagnostics = mergeDiagnosticsWithWarnings(diagnostics, result.warnings);

			const meta = outputMeta()
				.diagnostics(mergedDiagnostics?.summary ?? "", mergedDiagnostics?.messages ?? [])
				.get();

			return {
				content: [{ type: "text", text: resultText }],
				details: {
					diff: result.diff ?? "",
					firstChangedLine: result.first_changed_line,
					diagnostics: mergedDiagnostics,
					op: result.change.op,
					move: effRename,
					meta,
				},
			};
		}

		// ─────────────────────────────────────────────────────────────────
		// Replace mode execution
		// ─────────────────────────────────────────────────────────────────
		if (!isReplaceParams(params)) {
			throw new Error("Invalid edit parameters for replace mode.");
		}
		const { path, old_text, new_text, all } = params;

		enforcePlanModeWrite(this.session, path);

		if (path.endsWith(".ipynb")) {
			throw new Error("Cannot edit Jupyter notebooks with the Edit tool. Use the NotebookEdit tool instead.");
		}

		if (old_text.length === 0) {
			throw new Error("old_text must not be empty.");
		}

		const absolutePath = resolvePlanPath(this.session, path);

		if (!(await fs.exists(absolutePath))) {
			throw new Error(`File not found: ${path}`);
		}

		const rawContent = await fs.readFile(absolutePath, "utf-8");

		if (all) {
			const preflight = findMatch(rawContent, old_text, {
				allowFuzzy: this.#allowFuzzy,
				threshold: this.#fuzzyThreshold,
			});
			if (!preflight.match && (preflight.fuzzyMatches ?? 0) > 1) {
				throw new EditMatchError(path, old_text, preflight.closest, {
					allowFuzzy: this.#allowFuzzy,
					threshold: this.#fuzzyThreshold,
					fuzzyMatches: preflight.fuzzyMatches,
				});
			}
		}

		let result: LibEditResult;
		let operations: LibEditOperation[];
		try {
			const response = await this.#runLibEdit(
				"replace",
				{ path: absolutePath, old_text, new_text, all },
				[{ path: absolutePath, content: rawContent }],
				[{ absolute: absolutePath, display: path }],
			);
			result = response.result;
			operations = response.operations;
		} catch (error) {
			const message = error instanceof Error ? error.message : String(error);
			throw new Error(normalizeReplaceErrorMessage(message, path));
		}
		const diagnostics = await this.#applyLibEditOperations(operations, signal, batchRequest);
		this.#invalidateLibEditResult(result);

		const normalizedMessage = result.message.replaceAll(absolutePath, path);
		const resultText = normalizeReplaceResultMessage(normalizedMessage, path);

		const meta = outputMeta()
			.diagnostics(diagnostics?.summary ?? "", diagnostics?.messages ?? [])
			.get();

		return {
			content: [{ type: "text", text: resultText }],
			details: {
				diff: result.diff ?? "",
				firstChangedLine: result.first_changed_line,
				diagnostics,
				meta,
			},
		};
	}
}
